[build]
  functions = "functions/dist/cjs"

[[redirects]]
  from = "/api/myfxbook/*"
  to = "https://www.myfxbook.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200