version: 2.1

orbs:
  jira: circleci/jira@1.3.1
  codecov: codecov/codecov@1.1.3

jobs:
  install_build_lint_format_test_and_size:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn format
      - run: yarn test
      - run: yarn size
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - codecov/upload:
          file: "app/coverage/lcov.info"
          flags: "chrome"
      - codecov/upload:
          file: "functions/coverage/lcov.info"
          flags: "unittests"
      - codecov/upload:
          file: "packages/error-boundary/coverage/lcov.info"
          flags: "unittests"
      - codecov/upload:
          file: "packages/utils/coverage/lcov.info"
          flags: "unittests"
      - codecov/upload:
          file: "storybook/coverage/lcov.info"
          flags: "ui"
#  lint:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn lint
#
#  format:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn format
#
#  test:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn test
#  size:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn size

# Orchestrate our job run sequence
workflows:
  install_build_lint_format_test_and_size:
    jobs:
      - install_build_lint_format_test_and_size