version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo
orbs:
  jira: circleci/jira@1.3.1
steps:
  - checkout

  - restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  - run: yarn install

  - save_cache:
    paths:
      - node_modules
      - ~/.npm
      - ~/.cache
    key: v1-dependencies-{{ checksum "package.json" }}

  - run: yarn lint

  - run: yarn format

  - run: yarn test

  - run: yarn build
