version: 2.1
jobs:
  install_build_lint_format_test_and_size:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn format
      - run: yarn test
      - run: yarn size
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
#  lint:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn lint
#
#  format:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn format
#
#  test:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn test
#  size:
#    docker:
#      - image: circleci/node:12.9.1-browsers
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies-
#      - run: yarn install
#      - run: yarn size

orbs:
  jira: circleci/jira@1.3.1

# Orchestrate our job run sequence
workflows:
  install_build_lint_format_and_test:
    jobs:
      - install_build_lint_format_and_test